"""Added columns Products.Image, Products.Description

Revision ID: 1c00276b428f
Revises: 8bd91fc90cdd
Create Date: 2024-02-28 11:47:28.118130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c00276b428f'
down_revision = '8bd91fc90cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_column('Description')
        batch_op.drop_column('Image')

    # ### end Alembic commands ###
