"""Add Supplier model

Revision ID: 333d12ec9b0e
Revises: 8bd91fc90cdd
Create Date: 2024-02-15 19:47:53.082083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d12ec9b0e'
down_revision = '8bd91fc90cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('SupplierID', sa.Integer(), nullable=False),
    sa.Column('SupplierName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('SupplierID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    # ### end Alembic commands ###
