"""Adjust supplier-product relationship

Revision ID: 41b5d461ac2e
Revises: 333d12ec9b0e
Create Date: 2024-02-15 20:24:14.008218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b5d461ac2e'
down_revision = '333d12ec9b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'suppliers', ['SupplierID'], ['SupplierID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
